services:
  angular:
    image: charleneangular-angular:latest
    ports:
      - "4200:4200"
    volumes:
      - ./angular:/app
      - /app/node_modules
    command: ng serve --host 0.0.0.0 --port 4200 --poll 2000

  json-server:
    image: charleneangular-json-server
    volumes:
      - ./api:/data
    ports:
      - "3000:80"
    command: json-server --watch /data/db.json --port 80
