version: "3"
services:
  angular:
    images: charleneangular-angular:latest
    ports:
      - "4200:4200"
    volumes:
      - ./angular:/app
    stdin_open: true
    tty: true
    depends_on: 
    - backend

  json-server:
    build: ./api
    container_name: fake-api
    volumes:
      - ./api:/data
    ports:
      - "3000:80"
    command: json-server --watch /data/db.json --port 80
